version: '3.7'
services:
  src:
    build:
      context: .
      dockerfile: deployment/memory-django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
