name: Deploy using AWS SSM Send-Command

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo Hello world!

  # - uses: actions/checkout@v2
  # - name: AWS SSM Send Command
  # - uses: peterkimzz/aws-ssm-send-command@1.0.1
  #   with:
  #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCE sSS_KEY }}
  #     aws-region: eu-central-1b
  #     instance-ids: ${{ secrets.INSTANCE_ID }}
      #working-directory: /home/ubuntu/memory-backend
      #command: /bin/sh ./deploy.sh
